### PR TITLE
Issue 11: Rename package to io.pravega.connectors.presto

### LINKED ISSUE #11: Fix package names
The package name is incorrect, and it should be prefixed with `io.pravega` rather than `com.facebook`.

### PR DESCRIPTION
**Pull request by fpj**
Signed-off-by: Flavio Junqueira (fpj) <fpj@apache.org>

* Renames all packages to be prefixed with io.pravega.connectors.presto.

Fixes #11

### CODE REVIEW

**Review by adrdc — APPROVED** [review]

**Review by chipmaurer — COMMENTED** [review]
Were you able to start up a Presto server with these changes?

**Comment by fpj** [comment]
@chipmaurer I have been to start the coordinator with the changes in this PR:

```
2021-03-16T17:53:52.819+0100	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog properties etc/catalog/pravega.properties --
2021-03-16T17:53:52.824+0100	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog pravega --
2021-03-16T17:53:53.286+0100	INFO	main	Bootstrap	PROPERTY                       DEFAULT      RUNTIME                DESCRIPTION
2021-03-16T17:53:53.286+0100	INFO	main	Bootstrap	pravega.controller             ----         tcp://localhost:9090
2021-03-16T17:53:53.286+0100	INFO	main	Bootstrap	pravega.hide-internal-columns  true         true
2021-03-16T17:53:53.286+0100	INFO	main	Bootstrap	pravega.schema-registry        ----         http://localhost:9092
2021-03-16T17:53:53.286+0100	INFO	main	Bootstrap	pravega.table-description-dir  etc/pravega  etc/pravega
2021-03-16T17:53:54.103+0100	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Added catalog pravega using connector pravega --
2021-03-16T17:53:54.114+0100	INFO	main	com.facebook.presto.security.AccessControlManager	-- Loading system access control --
2021-03-16T17:53:54.115+0100	INFO	main	com.facebook.presto.security.AccessControlManager	-- Loaded system access control allow-all --
2021-03-16T17:53:54.115+0100	INFO	main	com.facebook.presto.storage.TempStorageManager	-- Loading temp storage --
2021-03-16T17:53:54.118+0100	INFO	main	com.facebook.presto.storage.TempStorageManager	-- Loaded temp storage local --
2021-03-16T17:53:54.120+0100	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========

```

Is there anything else you think I should be trying?

**Comment by chipmaurer** [comment]
Yes, it appears that with this PR merge: https://github.com/pravega/presto-connector/pull/14 that I cannot start the server from intelliJ.  Previously, 'build install' copied built jar and dependent jars to build/install/pravega.  Now, only the .gz file is being created, so running from intellij is not possible.

**Comment by fpj** [comment]
I'm not sure why you are referencing PR #14 here, they are independent PRs. Do you have any other comments on this PR?

**Comment by chipmaurer** [comment]
OK, I'll ask it this way.  Can you run the server from IntelliJ with these changes?

**Comment by fpj** [comment]
I'm running from command line, I'm following the instructions in: 

https://prestodb.io/docs/current/installation/deployment.html

**Review by chipmaurer — APPROVED** [review]

**Pull request merged**
